### ISSUE TITLE
Allow injection as service

### ISSUE THREAD

**Issue by st-h** [stingerlabs/ember-graph#76]
Ember data has switched to identifying the store as 'service:store', which is pretty nice as the store can be injected where it is needed. 

Can we change that convention in ember-graph as well?

the related discussion and PR for ember data can be found here:
https://github.com/emberjs/data/pull/3286

**Comment by gordonkristan** [comment]
Yeah, definitely. It's been on my list of things to do, but I wasn't in any hurry because I wasn't sure who was using this. :smile: I'll try to tackle this over the weekend. :+1:

**Comment by gordonkristan** [comment]
You can now access the store both ways. :+1:

**Comment by st-h** [comment]
Thank you. Works great.
